Commit

diff --git a/m1stack/run b/m1stack/run
--- a/m1stack/run
+++ b/m1stack/run
@@ -1,47 +1,62 @@
 #! /bin/bash
-getinput stack > student/MyStack.java
-cp Stack.java student/Stack.java
 
-cheat=$(cat student/MyStack.java | grep -c "java.util.Stack")
-if [ $cheat != "0" ]; then
-	feedback --result failed --feedback "You can't use java.util.Stack!"
-    exit 0
+#################
+# Configuration
+#################
+problemId="stack"
+studentCodeName="MyStack"
+interfaceName="Stack"
+testsName="StackTests"
+forbiddenClass="java.util.Stack"
+
+#################
+# Execution of tests
+#################
+getinput "${problemId}" > "student/${studentCodeName}.java"
+cp junit-4.12.jar student/junit-4.12.jar
+cp hamcrest-core-1.3.jar student/hamcrest-core-1.3.jar
+cp "${testsName}.java" "student/${testsName}.java"
+cp "${interfaceName}.java" "student/${interfaceName}.java"
+
+# We first check if the student didn't cheat
+if [ -n "${forbiddenClass}" ]; then
+	cheat=$(cat student/${studentCodeName}.java | grep -c "${forbiddenClass}")
+	if [ $cheat != "0" ]; then
+		feedback --result failed --feedback "We detected that you used ${forbiddenClass}, which is prohibited for this task."
+	    exit 0
+	fi
 fi
 
 # Compile the student code and parse it properly
-compilationMessage=$(javac student/Stack.java student/MyStack.java 2>&1)
+compilationMessage=$(javac -cp .:junit-4.12.jar student/${interfaceName}.java student/${studentCodeName}.java student/${testsName}.java 2>&1)
 compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
-compilationMessage=$(printf "Compilation of MyStack.java failed :\n::\n\n $compilationMessage")
-if [ ! -f student/MyStack.class ]; then
+compilationMessage=$(printf "Compilation of ${studentCodeName}.java failed :\n::\n\n $compilationMessage")
+if [ ! -f "student/${studentCodeName}.class" ]; then
     feedback --result failed --feedback "$compilationMessage"
     exit 0
 fi
 
-# Copy everything in the 'student' directory for run_student
-cp StackProps.scala student/StackProps.scala
-cp scalacheck.jar student/scalacheck.jar
 cd student
-scalac -cp .:scalacheck.jar StackProps.scala
-output=$(run_student scala -cp .:scalacheck.jar StackProps)
-retval=$?
+
+# We execute the tests
+output=$(run_student java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar "${testsName}")
+r=$?
 cd ..
 
-if [ "$retval" = "252" ]; then
-	feedback --result failed --feedback "Command was killed due to an out-of-memory"
-elif [ "$retval" = "253" ]; then
-	feedback --result timeout --feedback "Command timed out"
-elif [ "$retval" = "254" ]; then
-    feedback --result failed --feedback "Unfortunately, a runtime error occured"
-else
-	failed=$(echo "$output" | grep -c "Falsified")
-	passed=$(echo "$output" | grep -c "OK")
-	infos=$(echo "$output" | grep -o '! \w*.\w*')
+echo -e "${output}"
 
-	if [ "$failed" = "0" ] && [ "$passed" = "0" ]; then
-    	feedback --result failed --feedback "It seems like an internal error occured. If this persists, please contact your course administrator. "
-	elif [ "$failed" = "0" ]; then
-		feedback --result success --feedback "Congratulations, you passed the $passed tests!"
-	else
-		feedback --result failed --feedback "Unfortunately, you failed $failed tests out of $(($passed+$failed)) : $infos"
-	fi
+if [ "$r" = "252" ]; then
+	feedback --result failed --feedback "Command was killed due to an out-of-memory"
+elif [ "$r" = "253" ]; then
+	feedback --result timeout --feedback "Command timed out"
+elif [ "$r" = "254" ]; then
+      feedback --result failed --feedback "Unfortunately, a runtime error occured"
+elif [ "$r" = "1" ]; then
+	# Some tests have failed
+	feedback-result failed
+
+	feedback-msg -ae -m "${output}\n\nUnfortunately, your implementation didn't pass all tests"
+elif [ "$r" = "0" ]; then
+	# All tests passed !
+	feedback --result success --feedback "Congratulations, you passed the $passed tests!"
 fi
