Automatic synchronization from INGInious

diff --git a/m1stack/run b/m1stack/run
--- a/m1stack/run
+++ b/m1stack/run
@@ -1,29 +1,57 @@
 #! /bin/bash
-getinput stack > student/MyStack.java
-cp Stack.java student/Stack.java
 
-cheat=$(cat student/MyStack.java | grep -c "java.util.Stack")
+################
+# Configuration
+################
+problemId="stack"
+studentCodeName="MyStack"
+interfaceName="Stack"
+testsName="StackProps"
+forbiddenClasses=(
+	"java.util.Stack"
+)
+
+##################
+# Execution of the tests
+##################
+getinput "${problemId}" > "student/${studentCodeName}.java"
+cp "${interfaceName}" "student/${interfaceName}.java"
+
+cheat=$(cat student/${studentCodeName}.java | grep -c "")
 if [ $cheat != "0" ]; then
 	feedback --result failed --feedback "You can't use java.util.Stack!"
     exit 0
 fi
 
-# Compile the student code and parse it properly
+# Compile the student code
 compilationMessage=$(javac student/Stack.java student/MyStack.java 2>&1)
+retval=$?
 compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
 compilationMessage=$(printf "Compilation of MyStack.java failed :\n::\n\n $compilationMessage")
-if [ ! -f student/MyStack.class ]; then
+if [ "${retval}" != "0" ]; then
     feedback --result failed --feedback "$compilationMessage"
     exit 0
 fi
 
 # Copy everything in the 'student' directory for run_student
-cp StackProps.scala student/StackProps.scala
+cp ${testsName}.scala student/${testsName}.scala
 cp scalacheck.jar student/scalacheck.jar
 cd student
-scalac -cp .:scalacheck.jar StackProps.scala
-output=$(run_student scala -cp .:scalacheck.jar StackProps)
+
+# We compile the tests
+scalac -cp .:scalacheck.jar ${testsName}.scala
+if [ "$?" != 0 ]; then
+	feedback-result crash
+	feedback-msg -m "Error while compiling the tests. If it persists, contact the administrator of the course."
+	exit 1;
+fi
+
+# We run the tests
+output=$(run_student scala -cp .:scalacheck.jar ${testsName})
 retval=$?
+echo -e "${output}\n"
+echo -e "Scalacheck returned the value: ${retval}\n"
+
 cd ..
 
 if [ "$retval" = "252" ]; then
@@ -32,16 +60,11 @@ elif [ "$retval" = "253" ]; then
 	feedback --result timeout --feedback "Command timed out"
 elif [ "$retval" = "254" ]; then
     feedback --result failed --feedback "Unfortunately, a runtime error occured"
+elif [ "$retval" = "0" ]; then
+	# The student implementation passed the test
+	feedback --result success --feedback "Congratulations, your implementation passed the tests!"
 else
-	failed=$(echo "$output" | grep -c "Falsified")
-	passed=$(echo "$output" | grep -c "OK")
 	infos=$(echo "$output" | grep -o '! \w*.\w*')
-
-	if [ "$failed" = "0" ] && [ "$passed" = "0" ]; then
-    	feedback --result failed --feedback "It seems like an internal error occured. If this persists, please contact your course administrator. "
-	elif [ "$failed" = "0" ]; then
-		feedback --result success --feedback "Congratulations, you passed the $passed tests!"
-	else
-		feedback --result failed --feedback "Unfortunately, you failed $failed tests out of $(($passed+$failed)) : $infos"
-	fi
+	# Scalacheck returns the number of failed test
+	feedback --result failed --feedback "Unfortunately, you failed $retval tests: $infos"
 fi
