Automatic synchronization from INGInious

diff --git a/m1interpretertests/run b/m1interpretertests/run
--- a/m1interpretertests/run
+++ b/m1interpretertests/run
@@ -33,17 +33,22 @@ buggyFeedbacks=(
 # Execution of the tests
 ####################################
 
-getinput "${problemId}" > student/InterpreterTests.java
+getinput "${problemId}" > "student/$testName.java"
 cp junit-4.12.jar student/junit-4.12.jar
 cp hamcrest-core-1.3.jar student/hamcrest-core-1.3.jar
+cp "${name}.java" "student/${name}.java"
 cp "${interfaceName}.java" "student/${interfaceName}.java"
 cd student
 
-n=0 # number of tests passed (OK for Interpreter, FAILURES for BuggyInterpreters)
+incorrect=$(( $tot-1 ))
+n=0 # number of tests passed
 passOk=0
 failOk=0
 oldName="$name"
+feedbackMessages=""
 
+# This loop first checks with the correct implementation, and then
+# with the ${tot-1} incorrect ones
 for i in $(seq 1 $tot)
 do
 	cp "../${name}.java" "./${oldName}.java"
@@ -55,13 +60,12 @@ do
 	compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
 	compilationMessage=$(printf "Compilation of $testName.java failed :\n::\n\n $compilationMessage")
 	if [ ! -f "${testName}.class" ]; then
-    	feedback --result failed --feedback "$compilationMessage"
-    	exit 0
+		feedback --result failed --feedback "$compilationMessage"
+		exit 0
 	fi
 
 	output=$(run_student java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore "$testName")
-    retval=$?
-    
+	retval=$?
 	if [ "$retval" = "252" ]; then
 		feedback --result failed --feedback "Command was killed due to an out-of-memory"
 		exit 0
@@ -69,12 +73,12 @@ do
 		feedback --result timeout --feedback "Command timed out"
 		exit 0
 	elif [ "$retval" = "254" ]; then
-	      feedback --result failed --feedback "Unfortunately, a runtime error occured"
+		  feedback --result failed --feedback "Unfortunately, a runtime error occured"
 		exit 0
 	fi
 
 	failed=$(echo "$output" | grep -c "FAILURES")
-    passed=$(echo "$output" | grep -c "OK")
+	passed=$(echo "$output" | grep -c "OK")
 
 	if [ "$i" = "1" ]; then
 		# This is the first test, we're testing against the correct implementation
@@ -95,7 +99,7 @@ do
 			if [[ -z "$feedbackLine" ]]; then
 				feedbackLine="Failed test"
 			fi
-			feedback-msg -ae -m "Test #$index: $feedbackLine\n\n"
+			feedbackMessages="${feedbackMessages}Test #$index: $feedbackLine\n\n"
 		fi
 	fi
 done
@@ -106,12 +110,19 @@ if [ "$n" = "0" ]; then
 elif [ "$passOk" != "1" ]; then
 	feedback --result failed --feedback "You detected an error in a correct implementation"
 elif [ "$n" = "$tot" ]; then
-	feedback --grade 100 --result success --feedback "Congratulations, you passed the $n tests!"
+	feedback --grade 100 --result success --feedback "Congratulations, you passed the ${incorrect} tests!"
 else
-	incorrect=$(($tot-1))
+	errors=$(( incorrect - failOk ))
 	grade=$(( (100 * (failOk)) / $incorrect ))
 
 	feedback-grade $grade
 	feedback-result failed
+
+	# We only print the test feedbacks if the student has not more
+	# than 3 failed tests
+	if [ "$errors" -le "3" ]; then
+		feedback-msg -ae -m "${feedbackMessages}"
+	fi
+
 	feedback-msg -ae -m "You detected errors in only $failOk (out of $incorrect) incorrect implementations."
 fi
