Commit

diff --git a/m4_plagiarism_tests/run b/m4_plagiarism_tests/run
--- a/m4_plagiarism_tests/run
+++ b/m4_plagiarism_tests/run
@@ -6,66 +6,96 @@
 # 4) incrementalHashCode returns the wrong hash (inc by 1)
 # 5) get(key) returns the right element the first time, and then always this same (wrong) element
 
-tot=6 # number of tests
+###################################
+# Test configuration
+###################################
+
+tot=10 # number of tests
+problemId="plagiarism_tests"
 name="HashMap"
 testName="HashMapTests"
-word="map"
+interfaceName="map"
+buggyName="BuggyHashMap"
+buggyFeedbacks=(
+	""
+	""
+	""
+	"Failed incrementalHashCode() test"
+	"Methods should be tested multiple times with different elements to make there is no side-effects between calls"
+)
 
-getinput plagiarism_tests > "student/$testName.java"
+####################################
+# Execution of the tests
+####################################
+getinput "${problemId}" > "student/$testName.java"
 cp junit-4.12.jar student/junit-4.12.jar
 cp hamcrest-core-1.3.jar student/hamcrest-core-1.3.jar
-cp HashMap.java ./student
-cp MapInterface.java ./student
+cp "${name}.java" "student/${name}.java"
+cp "${interfaceName}.java" "student/${interfaceName}.java"
 cd student
 
+incorrect=$(( $tot-1 ))
 n=0 # number of tests passed
 passOk=0
 failOk=0
-buggyName="Buggy$name"
 oldName="$name"
+feedbackMessages=""
 
+# This loop first checks with the correct implementation, and then
+# with the ${tot-1} incorrect ones
 for i in $(seq 1 $tot)
 do
-	
 	cp "../${name}.java" "./${oldName}.java"
 	name="${buggyName}${i}"
-
 	javac "${oldName}.java"
 
 	# Compile the student code and parse it properly
 	compilationMessage=$(javac -cp .:junit-4.12.jar "${testName}.java" 2>&1)
+	r=$?
 	compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
 	compilationMessage=$(printf "Compilation of $testName.java failed :\n::\n\n $compilationMessage")
-	if [ ! -f "$testName.class" ]; then
-    	feedback --result failed --feedback "$compilationMessage"
-    	exit 0
+	if [ "$r" = "1" ]; then
+		feedback --result failed --feedback "$compilationMessage"
+		exit 0
 	fi
 
 	output=$(run_student java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore "$testName")
-    r=$?
-    
-	if [ "$r" = "252" ]; then
+	retval=$?
+	if [ "$retval" = "252" ]; then
 		feedback --result failed --feedback "Command was killed due to an out-of-memory"
 		exit 0
-	elif [ "$r" = "253" ]; then
+	elif [ "$retval" = "253" ]; then
 		feedback --result timeout --feedback "Command timed out"
 		exit 0
-	elif [ "$r" = "254" ]; then
-	      feedback --result failed --feedback "Unfortunately, a runtime error occured"
+	elif [ "$retval" = "254" ]; then
+		  feedback --result failed --feedback "Unfortunately, a runtime error occured"
 		exit 0
 	fi
 
 	failed=$(echo "$output" | grep -c "FAILURES")
-    passed=$(echo "$output" | grep -c "OK")
+	passed=$(echo "$output" | grep -c "OK")
 
-	if [ "$i" = "1" ] && [ "$failed" = "0" ] && [ "$passed" != "0" ]; then
-		((n++))
-		((passOk++))
-	fi
+	if [ "$i" != "0" ]; then
+		# This is the first test, we're testing against the correct implementation
+		if [ "$failed" = "0" ] && [ "$passed" != "0" ]; then
+			((n++))
+			((passOk++))
+		fi
 
-	if [ "$i" != "1" ] && [ "$failed" = "1" ] && [ "$passed" = "0" ]; then
-		((n++))
-		((failOk++))
+	else
+		# We're testing against an incorrect implementation
+		if [ "$failed" = "1" ] && [ "$passed" = "0" ]; then
+			((n++))
+			((failOk++))
+		else
+			# We add a feedback message for the user
+			index=$((i - 1))
+			feedbackLine=${buggyFeedbacks[$index-1]}
+			if [[ -z "$feedbackLine" ]]; then
+				feedbackLine="Failed test"
+			fi
+			feedbackMessages="${feedbackMessages}Test #$index: $feedbackLine\n\n"
+		fi
 	fi
 done
 cd ..
@@ -73,11 +103,21 @@ cd ..
 if [ "$n" = "0" ]; then
 	feedback --result failed --feedback "It seems like an internal error occured. If this persists, please contact your course administrator. "
 elif [ "$passOk" != "1" ]; then
-	feedback --result failed --feedback "you detected an error in a correct $word implementation"
+	feedback --result failed --feedback "You detected an error in a correct implementation"
 elif [ "$n" = "$tot" ]; then
-	feedback --result success --feedback "Congratulations, you passed the $n tests!"
+	feedback --grade 100 --result success --feedback "Congratulations, you passed the ${incorrect} tests!"
 else
-    incorrect=$(($tot-1))
-	lack=$(($incorrect-$failOk))
-	feedback --result failed --feedback "Unfortunately, you didn't detect errors in $lack (out of $incorrect) incorrect ${word} implementations. "
+	errors=$(( incorrect - failOk ))
+	grade=$(( (100 * (failOk)) / $incorrect ))
+
+	feedback-grade $grade
+	feedback-result failed
+
+	# We only print the test feedbacks if the student has not more
+	# than 3 failed tests
+	if [ "$errors" -le "3" ]; then
+		feedback-msg -ae -m "${feedbackMessages}"
+	fi
+
+	feedback-msg -ae -m "You detected errors in only $failOk (out of $incorrect) incorrect implementations."
 fi
