Commit

diff --git a/m3tests/run b/m3tests/run
--- a/m3tests/run
+++ b/m3tests/run
@@ -1,11 +1,11 @@
 #! /bin/bash
-# BuggySearchTree : 
+# BuggySearchTree :
 # 1 : !isEmpty()
 # 2 : remove doesn't remove anything
 # 3 : constructor with String argument does same as no argument constructor
 # 4 : constructor with String argument only treats the 2 first lines of the file
-# 5 : ceilingEntry and floorEntry are inversed. 
-# 6 : firstEntry() actually returns the second entry. 
+# 5 : ceilingEntry and floorEntry are inversed.
+# 6 : firstEntry() actually returns the second entry.
 # 7 : getOrdered doesn't sort the songs
 # 8 : entriesBetween returns entries STRICTLY in the range (should be inclusive)
 # 9 : entriesBetween returns entries from 'lowest' (but to the max, not to 'highest')
@@ -41,19 +41,22 @@ cp songs.txt student/songs.txt
 ####################################
 # Execution of the tests
 ####################################
-getinput "${problemId}" > "student/${testName}.java"
+getinput "${problemId}" > "student/$testName.java"
 cp junit-4.12.jar student/junit-4.12.jar
 cp hamcrest-core-1.3.jar student/hamcrest-core-1.3.jar
 cp "${name}.java" "student/${name}.java"
 cp "${interfaceName}.java" "student/${interfaceName}.java"
 cd student
 
+incorrect=$(( $tot-1 ))
 n=0 # number of tests passed
 passOk=0
 failOk=0
 oldName="$name"
 feedbackMessages=""
 
+# This loop first checks with the correct implementation, and then
+# with the ${tot-1} incorrect ones
 for i in $(seq 1 $tot)
 do
 	cp "../${name}.java" "./${oldName}.java"
@@ -62,31 +65,31 @@ do
 
 	# Compile the student code and parse it properly
 	compilationMessage=$(javac -cp .:junit-4.12.jar "${testName}.java" 2>&1)
+	r=$?
 	compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
-	compilationMessage=$(printf "Compilation of ${testName}.java failed :\n::\n\n $compilationMessage")
-	if [ ! -f "${testName}.class" ]; then
-    	feedback --result failed --feedback "$compilationMessage"
-    	exit 0
+	compilationMessage=$(printf "Compilation of $testName.java failed :\n::\n\n $compilationMessage")
+	if [ "$r" = "1" ]; then
+		feedback --result failed --feedback "$compilationMessage"
+		exit 0
 	fi
 
 	output=$(run_student java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore "$testName")
-    r=$?
-    
-	if [ "$r" = "252" ]; then
+	retval=$?
+	if [ "$retval" = "252" ]; then
 		feedback --result failed --feedback "Command was killed due to an out-of-memory"
 		exit 0
-	elif [ "$r" = "253" ]; then
+	elif [ "$retval" = "253" ]; then
 		feedback --result timeout --feedback "Command timed out"
 		exit 0
-	elif [ "$r" = "254" ]; then
-	      feedback --result failed --feedback "Unfortunately, a runtime error occured"
+	elif [ "$retval" = "254" ]; then
+		  feedback --result failed --feedback "Unfortunately, a runtime error occured"
 		exit 0
 	fi
 
 	failed=$(echo "$output" | grep -c "FAILURES")
-    passed=$(echo "$output" | grep -c "OK")
+	passed=$(echo "$output" | grep -c "OK")
 
-	if [ "$i" = "1" ]; then
+	if [ "$i" != "0" ]; then
 		# This is the first test, we're testing against the correct implementation
 		if [ "$failed" = "0" ] && [ "$passed" != "0" ]; then
 			((n++))
@@ -112,13 +115,12 @@ done
 cd ..
 
 if [ "$n" = "0" ]; then
-	feedback --result failed --feedback "It seems like an internal error occured. If this persists, please contact your course administrator."
+	feedback --result failed --feedback "It seems like an internal error occured. If this persists, please contact your course administrator. "
 elif [ "$passOk" != "1" ]; then
 	feedback --result failed --feedback "You detected an error in a correct implementation"
 elif [ "$n" = "$tot" ]; then
-	feedback --grade 100 --result success --feedback "Congratulations, you passed the $n tests!"
+	feedback --grade 100 --result success --feedback "Congratulations, you passed the ${incorrect} tests!"
 else
-	incorrect=$(( $tot-1 ))
 	errors=$(( incorrect - failOk ))
 	grade=$(( (100 * (failOk)) / $incorrect ))
 
