Automatic synchronization from INGInious

diff --git a/m1interpreter/run b/m1interpreter/run
--- a/m1interpreter/run
+++ b/m1interpreter/run
@@ -1,44 +1,79 @@
 #! /bin/bash
-getinput interpreter > student/Interpreter.java
-cp InterpreterInterface.java student/InterpreterInterface.java
 
-# Compile the student code and parse it properly
-compilationMessage=$(javac student/InterpreterInterface.java student/Interpreter.java 2>&1)
+################
+# Configuration
+################
+problemId="interpreter"
+studentCodeName="Interpreter"
+interfaceName="InterpreterInterface"
+testsName="InterpreterProps"
+forbiddenClasses=(
+
+)
+
+##################
+# Execution of the tests
+##################
+getinput "${problemId}" > "student/${studentCodeName}.java"
+cp "${interfaceName}.java" "student/${interfaceName}.java"
+
+# We check if the student cheated
+for $forbiddenClass in "${forbiddenClasses[@]}"
+do
+	cheat=$(cat "student/${studentCodeName}.java" | grep -c "${forbiddenClass}")
+	echo -e "${cheat}"
+	if [ "$cheat" != "0" ]; then
+		feedback --result failed --feedback "We detected the use of ${forbiddenClass}, which is prohibited for this test."
+	    exit 1
+	fi
+done
+
+# Compile the student code
+compilationMessage=$(javac student/${interfaceName}.java student/${studentCodeName}.java 2>&1)
+retval=$?
 compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
-compilationMessage=$(printf "Compilation of Interpreter.java failed :\n::\n\n $compilationMessage")
-if [ ! -f student/Interpreter.class ]; then
+compilationMessage=$(printf "Compilation of ${studentCodeName}.java failed :\n::\n\n $compilationMessage")
+if [ "${retval}" != "0" ]; then
     feedback --result failed --feedback "$compilationMessage"
-    exit 0
+    exit 1
 fi
 
 # Copy everything in the 'student' directory for run_student
-cp InterpreterProps.scala student/InterpreterProps.scala
-cp GeneratorPostScript.java student/GeneratorPostScript.java
-cp MyInterpreter.java student/MyInterpreter.java
+cp ${testsName}.scala student/${testsName}.scala
 cp scalacheck.jar student/scalacheck.jar
 cd student
-javac GeneratorPostScript.java MyInterpreter.java
-scalac -cp .:scalacheck.jar InterpreterProps.scala
-output=$(run_student scala -cp .:scalacheck.jar InterpreterProps)
-r=$?
+
+# We compile the tests
+scalac -cp .:scalacheck.jar ${testsName}.scala
+if [ "$?" != 0 ]; then
+	feedback-result failed
+	feedback-msg -m "Error while compiling the tests. If it persists, contact the administrator of the course."
+	exit 1
+fi
+
+# We run the tests
+output=$(run_student scala -cp .:scalacheck.jar ${testsName})
+retval=$?
+echo -e "${output}\n"
+echo -e "Scalacheck returned the value: ${retval}\n"
+
 cd ..
 
-if [ "$r" = "252" ]; then
+if [ "$retval" = "252" ]; then
 	feedback --result failed --feedback "Command was killed due to an out-of-memory"
-elif [ "$r" = "253" ]; then
+elif [ "$retval" = "253" ]; then
 	feedback --result timeout --feedback "Command timed out"
-elif [ "$r" = "254" ]; then
-      feedback --result failed --feedback "Unfortunately, a runtime error occured"
+elif [ "$retval" = "254" ]; then
+    feedback --result failed --feedback "Unfortunately, a runtime error occured"
+elif [ "$retval" = "0" ]; then
+	# The student implementation passed the test
+	feedback --result success --feedback "Congratulations, your implementation passed the tests!"
 else
-    failed=$(echo "$output" | grep -c "Falsified")
-	passed=$(echo "$output" | grep -c "OK")
-    infos=$(echo "$output" | grep -o '! \w*.\w*')
-
-	if [ "$failed" = "0" ] && [ "$passed" = "0" ]; then
-    	feedback --result failed --feedback "It seems like an internal error occured. If this persists, please contact your course administrator. "
-	elif [ "$failed" = "0" ]; then
-		feedback --result success --feedback "Congratulations, you passed the $passed tests!"
-	else
-		feedback --result failed --feedback "Unfortunately, you failed $failed tests out of $(($passed+$failed)) : $infos"
-	fi
+	infos=$(echo "$output" | grep -o '! \w*.\w*')
+	# Scalacheck returns the number of failed test
+	feedback-result failed
+	feedback-msg -ae -m "Unfortunatley, you failed ${retval} tests: \n\n"
+	feedback-msg -ae -m "${output}"
+	#feedback-msg
+	#feedback --result failed --feedback "Unfortunately, you failed $retval tests: $infos"
 fi
