Commit

diff --git a/m3orderedmap/run b/m3orderedmap/run
--- a/m3orderedmap/run
+++ b/m3orderedmap/run
@@ -1,61 +1,72 @@
 #! /bin/bash
-getinput ordered_map > student/SearchTree.java
-cp OrderedMap.java student/OrderedMap.java
 
-patterns="java.util.TreeMap|java.util.concurrent.ConcurrentSkipListMap"
-cheat=$(cat student/SearchTree.java | grep -c -E "$patterns")
-if [ $cheat != "0" ]; then
-	feedback --result failed --feedback "You can't use an exising Ordered Map implementation!"
-    exit 0
-fi
+#################
+# Configuration
+#################
+problemId="ordered_map"
+studentCodeName="SearchTree"
+interfaceName="OrderedMap"
+testsName="OrderedMapTests"
+forbiddenClasses=(
+	"java.util.TreeMap"
+	"java.util.concurrent.ConcurrentSkipListMap"
+	"Arrays.sort"
+)
 
-cheat2=$(cat student/SearchTree.java | grep -c "Arrays.sort")
-if [ $cheat2 != "0" ]; then
-	feedback --result failed --feedback "You can't use Arrays.sort, you must implement the QuickSort algorithm yourself!"
-    exit 0
-fi
+# SPECIFIC FOR THIS TEST
+cp songs.txt student/songs.txt
+
+#################
+# Execution of tests
+#################
+getinput "${problemId}" > "student/${studentCodeName}.java"
+cp junit-4.12.jar student/junit-4.12.jar
+cp hamcrest-core-1.3.jar student/hamcrest-core-1.3.jar
+cp "${testsName}.java" "student/${testsName}.java"
+cp "${interfaceName}.java" "student/${interfaceName}.java"
+
+# We first check if the student didn't cheat
+for forbiddenClass in "${forbiddenClasses[@]}"
+do
+	cheat=$(cat student/${studentCodeName}.java | grep -c "${forbiddenClass}")
+	if [ $cheat != "0" ]; then
+		feedback --result failed --feedback "We detected that you used ${forbiddenClass}, which is prohibited for this task."
+	    exit 1
+	fi
+done
 
 # Compile the student code and parse it properly
-compilationMessage=$(javac student/SearchTree.java student/OrderedMap.java 2>&1)
+compilationMessage=$(javac -cp .:junit-4.12.jar student/${interfaceName}.java student/${studentCodeName}.java student/${testsName}.java 2>&1)
+r=$?
 compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
-compilationMessage=$(printf "Compilation of SearchTree.java failed :\n::\n\n $compilationMessage")
-if [ ! -f student/SearchTree.class ]; then
+compilationMessage=$(printf "Compilation of ${studentCodeName}.java failed :\n::\n\n $compilationMessage")
+
+if [ "$r" != "0" ]; then
     feedback --result failed --feedback "$compilationMessage"
     exit 0
 fi
 
-# Copy everything in the 'student' directory for run_student
-cp OrderedMapProps.scala student/OrderedMapProps.scala
-cp scalacheck.jar student/scalacheck.jar
-cp songs.txt student/songs.txt
 cd student
-scalac -cp .:scalacheck.jar OrderedMapProps.scala
 
-if [ ! -f OrderedMapProps.class ]; then
-    feedback --result failed --feedback "An error occured during the compilation of the test script. Make sure your class follows the specifications. Does it correctly implement the interface, with the requested constructors ? "
-    exit 0
-fi
-
-output=$(run_student scala -cp .:scalacheck.jar -J-Xmx2g -J-Xms2g OrderedMapProps)
+# We execute the tests
+output=$(run_student java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar "${testsName}")
 r=$?
 cd ..
+
+echo -e "${output}"
 
 if [ "$r" = "252" ]; then
 	feedback --result failed --feedback "Command was killed due to an out-of-memory"
 elif [ "$r" = "253" ]; then
 	feedback --result timeout --feedback "Command timed out"
 elif [ "$r" = "254" ]; then
-    feedback --result failed --feedback "Unfortunately, a runtime error occured"
-else
-	failed=$(echo "$output" | grep -c "Falsified")
-	passed=$(echo "$output" | grep -c "OK")
-	infos=$(echo "$output" | grep -o '! \w*.\w*')
+      feedback --result failed --feedback "Unfortunately, a runtime error occured"
+elif [ "$r" = "1" ]; then
+	# Some tests have failed
+	feedback-result failed
 
-	if [ "$failed" = "0" ] && [ "$passed" = "0" ]; then
-    	feedback --result failed --feedback "It seems like an internal error occured. Maybe a Stack Overflow, or just INGInious being overloaded. If this persists, please contact your course administrator. "
-	elif [ "$failed" = "0" ]; then
-		feedback --result success --feedback "Congratulations, you passed the $passed tests! "
-	else
-		feedback --result failed --feedback "Unfortunately, you failed $failed tests out of $(($passed+$failed)) : $infos"
-	fi
+	feedback-msg -ae -m "${output}\n\nUnfortunately, your implementation didn't pass all tests"
+elif [ "$r" = "0" ]; then
+	# All tests passed !
+	feedback --result success --feedback "Congratulations, you passed the $passed tests!"
 fi
